# Generated by Django 2.2.6 on 2021-01-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user_name',
            new_name='username',
        ),
    ]
