# Generated by Django 2.2.6 on 2021-01-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210104_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Vendor'),
        ),
    ]
