# Generated by Django 2.2.17 on 2021-01-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210107_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
    ]
