# Generated by Django 2.2.17 on 2021-01-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210111_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoilage_item',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='spoilage_item',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
    ]
