# Generated by Django 2.2.6 on 2021-01-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210111_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
