# Generated by Django 2.2.17 on 2021-01-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20210112_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='sales_order',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='spoilage',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
    ]
