# Generated by Django 2.2.17 on 2021-01-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210114_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoilage',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='sales_item',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='sales_item',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='spoilage',
            name='total_lost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='spoilage_item',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='spoilage_item',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
    ]
