# Generated by Django 2.2.6 on 2021-02-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210127_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customer', models.ManyToManyField(to='app.Customer')),
                ('product', models.ManyToManyField(to='app.Product')),
                ('purchase_order', models.ManyToManyField(to='app.Purchase_Order')),
                ('sales_order', models.ManyToManyField(to='app.Sales_Order')),
                ('spoilage', models.ManyToManyField(to='app.Spoilage')),
                ('transfer', models.ManyToManyField(to='app.Transfer')),
                ('vendor', models.ManyToManyField(to='app.Vendor')),
                ('warehouse', models.ManyToManyField(to='app.Warehouse')),
            ],
        ),
    ]
