# Generated by Django 2.2.17 on 2021-02-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210214_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='turnover',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True),
        ),
    ]
