# Generated by Django 2.2.17 on 2021-02-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210214_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='customer',
            field=models.ManyToManyField(blank=True, to='app.Customer'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='product',
            field=models.ManyToManyField(blank=True, to='app.Product'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='purchase_order',
            field=models.ManyToManyField(blank=True, to='app.Purchase_Order'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='sales_order',
            field=models.ManyToManyField(blank=True, to='app.Sales_Order'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='spoilage',
            field=models.ManyToManyField(blank=True, to='app.Spoilage'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='transfer',
            field=models.ManyToManyField(blank=True, to='app.Transfer'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='app.Vendor'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='warehouse',
            field=models.ManyToManyField(blank=True, to='app.Warehouse'),
        ),
    ]
